name: slip_0010_ed25519
version: 3.2.0

description: BIP-0032 like derivation for ed25519 curve following SLIP-0010
repository: https://github.com/Eucalyptus-Labs/slip_0010_ed25519

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  pinenacl: ^0.5.1
  crypto: ^3.0.3

dev_dependencies:
  test: ^1.24.3
#  dependency_validator: ^3.2.2
  convert: ^3.1.1
