name: slip_0010_ed25519
version: 0.0.1

description: BIP-0032 like derivation for ed25519 curve
repository: https://github.com/Eucalyptus-Labs/dart-ed25519-hd-key

environment:
  sdk: '>=2.18.4 <=3.0.0'

dependencies:
  pinenacl: ^0.5.1

dev_dependencies:
  test: ^1.22.1
#  convert: ^3.0.0
